site_name: Appyx Comm

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: eryxcoop/appyx-comm
repo_url: https://github.com/eryxcoop/appyx-comm


nav:
  - Appyx: index.md
  - Getting Started: getting-started.md
  - User Guide: lib.md
  - Examples: examples.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences